apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: wishlist-app
  template:
    metadata:
      labels:
        component: wishlist-app
    spec:
      containers:
        - name: wishlist-app-container
          image: andj712/lista_zelja:latest
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: '6379'
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USER
              value: hello_flask
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: hello_flask_db
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
        - name: fluentd-sidecar
          image: fluent/fluentd:v1.17.0-1.0
          volumeMounts:
            - name: logs-volume
              mountPath: /var/log/app
      volumes:
        - name: logs-volume
          emptyDir: {}
